name: qutem
description: quick template engine
version: 0.5.2
homepage: https://github.com/sasuw/qutem

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  yaml: ^3.1.2
  args: ^2.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.9
  mockito: ^5.4.4
  build_runner: ^2.4.7