name: qutem
description: quick template engine
version: 0.4.1
homepage: https://github.com/sasuw/qutem

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
