name: qutem
description: A sample command-line application.
version: 0.2.1
homepage: https://github.com/sasuw/qutem

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
